// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/kvh.h"
#include <Rcpp.h>

using namespace Rcpp;

// kvh_read
List kvh_read(string& fn);
RcppExport SEXP _kvh_kvh_read(SEXP fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string& >::type fn(fnSEXP);
    rcpp_result_gen = Rcpp::wrap(kvh_read(fn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kvh_kvh_read", (DL_FUNC) &_kvh_kvh_read, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_kvh(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
