# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Parse file in KVH format
#'
#' Returns a list with names formed form kvh keys and values formed from kvh values
#' If a kvh value has sub-keys, it is returned as a nested list. Otherwise it is
#' returned as a character string.
#'
#' @param fn character kvh file name.
#' @export
kvh_read <- function(fn) {
    .Call(`_kvh_kvh_read`, fn)
}

